# Setup
name:             Cadence
description:      My rhythm of thoughts.
meta_description: "Cadence, my rhythm of thoughts"
url:              https://brianpho.com
baseurl:          # does not include hostname
author:           "Brian Pho"

# Plugins
plugins:          [jekyll-paginate]

# Conversion
markdown:         kramdown
highlighter:      rouge

# Outputting
logo: false
paginate:         5
