# Setup
name:             Cadence
description:      My rhythm of thoughts.
meta_description: "Cadence, my rhythm of thoughts."
url:              https://brianpho.com
baseurl:          # does not include hostname
author:           "Brian Pho"

# Filtering Content
show_drafts:      null
limit_posts:      0
future:           false
unpublished:      false      

# Plugins
whitelist:        []
plugins:          [jekyll-paginate]

# Conversion
markdown:         kramdown
highlighter:      rouge

# Outputting
permalink:        date
logo: false
paginate:         5
paginate_path:    /page:num
timezone:         null

quiet:            false
verbose:          false
defaults:         []
